### ISSUE TITLE
cannot find mat files

### ISSUE THREAD

**Issue by dhanashri-innovision** [BoysTownorg/chapro#6]
Hi,
I was trying to run the codes tst_ifsc and gha_demo, but matlab is giving the error that it cannot find mat files for the same.
can you upload them????

**Comment by neeste** [comment]
The MAT files (that the MATLAB scripts are trying to find) are created by running the executable files tst_ifsc and gha_demo.

All chapro tests, including tst_* and gha_demo, require the following steps.

  *   Compile the C code to obtain an executable file that performs the test.
  *   Run the executable code to perform the test, which produces either a MAT or WAV output file.
  *   Run the corresponding MATLAB script to display the contents of the output file.

For example, the following steps perform the tst_ifsc test.

  *   compile tst_ifsc.c
  *   run tst_ifsc, which produces the output file tst_ifsc.mat
  *   run tst_ifsc.m in MATLAB to view the contents of tst_ifsc.mat.

Hope this helps.

-- Stephen Neely

**Comment by neeste** [comment]
See comment above.
