### ISSUE TITLE
sigpro.h

### ISSUE THREAD

**Issue by kobecccccc** [BoysTownorg/chapro#7]
Hi,
Thanks for your work. I try to build the project in vs2015, but  I can't find 'sigpro.h', can you upload it?

**Comment by kobecccccc** [comment]
I have found in chapro.pdf.

**Comment by neeste** [comment]
CHAPRO depends on ARSC and SIGPRO, which have separate repos at https://github.com/BoysTownorg. Please install ARSC and SIGPRO before installing CHAPRO.

________________________________
